version: '3.7'

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: "Networking_System"
      POSTGRES_USER: "Hemlocked"
      POSTGRES_PASSWORD: "dbms@123"
    volumes:
      - ./pgdata:/var/lib/postgresql/data



