 users=[ 
    { username: "alice.baker1", email: "alice.baker1@example.com", password: "QwErt123" }, 
    { username: "charlie.delta1", email: "charlie.delta1@example.com", password: "RtyUi345" }, 
    { username: "erik.falk1", email: "erik.falk1@example.com", password: "AsdFg567" }, 
    { username: "gustav.gunnarsson1", email: "gustav.gunnarsson1@example.com", password: "ZxcCv789" }, 
    { username: "henrik.hansen1", email: "henrik.hansen1@example.com", password: "LkjHg900" }, 
    { username: "isak.johansson1", email: "isak.johansson1@example.com", password: "PöPsRa234" }, 
    { username: "julia.karlsson1", email: "julia.karlsson1@example.com", password: "QaWeYz123" }, 
    { username: "karin.lindström1", email: "karin.lindström1@example.com", password: "UioPx456" }, 
    { username: "magnus.martensson1", email: "magnus.martensson1@example.com", password: "JklHg987" }, 
    { username: "nadja.nilsson1", email: "nadja.nilsson1@example", password:"vYUV66f9"},
    { username: "HappyCat", email: "happycat123@gmail.com", password: "password123" },
    { username: "SunnyDog", email: "sunnydog456@gmail.com", password: "securepass789" },
    { username: "LuckyBird",email: "luckybird789@yahoo.com",password: "p@ssw0rd!" },
    { username: "CoolFish",email: "coolfish432@outlook.com",password: "strongPass" },
    { username: "CreativeTiger",email:"creativetiger111@example.com", password: "mypassword123" },
    { username: "AlphaUser123",email: "alphauser123@example.com",password: "P@ssw0rd" },
    { username: "BetaUser456", email: "betauser456@example.com", password: "Secret123" },
    { username: "GammaUser789",email: "gammauser789@example.com",password: "StrongPassword" },
    { username: "DeltaUser001",email: "deltauser001@example.com",password: "RandomPass456" },
    {username:"EpsilonUser234",email:"epsilonuser234@example.com",password: "Secure123" },
    { username: "ZetaUser567", email: "zetauser567@example.com", password: "NewPass789" },
    { username: "EtaUser890",  email: "etauser890@example.com",  password: "RandomPass123" },
    { username: "ThetaUser345",email: "thetauser345@example.com",password: "SecurePass789" },
    { username: "IotaUser678", email: "iotauser678@example.com", password: "StrongPass123" },
    { username: "KappaUser912",email: "kappauser912@example.com",password: "NewPassword456" },
    { username:"LambdaUser543",email:"lambdauser543@example.com",password: "P@ssword789" },
    { username: "MuUser210",   email: "muuser210@example.com",   password: "SecretPassword123" },
    { username: "NuUser987",   email: "nuuser987@example.com",   password: "RandomPassword456" },
    { username: "XiUser654",   email: "xiuser654@example.com",   password: "SecurePassword789" },
    {username:"OmicronUser321",email:"omicronuser321@example.com",password: "StrongPassword123" },
    { username: "PiUser876",   email: "piuser876@example.com",    password: "NewPassword789" },
    { username: "RhoUser543",  email: "rhouser543@example.com",   password: "RandomPassword123" },
    { username: "SigmaUser210",email: "sigmauser210@example.com", password: "P@ssword789" },
    { username: "TauUser987",  email: "tauuser987@example.com",   password: "SecretPass123" },
    {username:"UpsilonUser654",email:"upsilonuser654@example.com",password: "StrongPass789" }
  
]

